export type ErrorVariant = 'not-found' | 'bad-gateway' | 'service-unavailable';

interface Props {
	variant: ErrorVariant;
}

export default function ErrorIllustration({ variant }: Props) {
	return (
		<svg
			className='error-illustration'
			viewBox='0 0 200 160'
			fill='none'
			xmlns='http://www.w3.org/2000/svg'
		>
			{variant === 'not-found' && <NotFoundArt />}
			{variant === 'bad-gateway' && <BadGatewayArt />}
			{variant === 'service-unavailable' && <ServiceUnavailableArt />}
		</svg>
	);
}

function NotFoundArt() {
	return (
		<>
			<circle
				cx='100'
				cy='80'
				r='70'
				fill='var(--pl)'
				opacity='0.5'
			/>
			<rect
				x='60'
				y='40'
				width='70'
				height='90'
				rx='10'
				fill='var(--sur)'
				stroke='var(--bdr)'
				strokeWidth='2.5'
			/>
			<line
				x1='74'
				y1='62'
				x2='116'
				y2='62'
				stroke='var(--bdr)'
				strokeWidth='3'
				strokeLinecap='round'
			/>
			<line
				x1='74'
				y1='76'
				x2='116'
				y2='76'
				stroke='var(--bdr)'
				strokeWidth='3'
				strokeLinecap='round'
			/>
			<line
				x1='74'
				y1='90'
				x2='100'
				y2='90'
				stroke='var(--bdr)'
				strokeWidth='3'
				strokeLinecap='round'
			/>
			<circle
				cx='128'
				cy='100'
				r='26'
				fill='var(--sur)'
				stroke='var(--p)'
				strokeWidth='5'
			/>
			<text
				x='128'
				y='109'
				textAnchor='middle'
				fontSize='22'
				fontWeight='700'
				fill='var(--p)'
			>
				?
			</text>
			<line
				x1='147'
				y1='119'
				x2='164'
				y2='136'
				stroke='var(--p)'
				strokeWidth='6'
				strokeLinecap='round'
			/>
			<circle
				cx='46'
				cy='46'
				r='4'
				fill='var(--acc)'
			/>
			<circle
				cx='158'
				cy='52'
				r='3'
				fill='var(--acc)'
				opacity='0.7'
			/>
		</>
	);
}

function BadGatewayArt() {
	return (
		<>
			<circle
				cx='100'
				cy='80'
				r='70'
				fill='var(--purple-l)'
				opacity='0.45'
			/>
			<rect
				x='20'
				y='60'
				width='52'
				height='60'
				rx='8'
				fill='var(--sur)'
				stroke='var(--bdr)'
				strokeWidth='2.5'
			/>
			<rect
				x='128'
				y='60'
				width='52'
				height='60'
				rx='8'
				fill='var(--sur)'
				stroke='var(--bdr)'
				strokeWidth='2.5'
			/>
			<circle
				cx='46'
				cy='76'
				r='4'
				fill='var(--p)'
			/>
			<circle
				cx='154'
				cy='76'
				r='4'
				fill='var(--mut)'
				opacity='0.5'
			/>
			<line
				x1='34'
				y1='92'
				x2='58'
				y2='92'
				stroke='var(--bdr)'
				strokeWidth='3'
				strokeLinecap='round'
			/>
			<line
				x1='34'
				y1='102'
				x2='58'
				y2='102'
				stroke='var(--bdr)'
				strokeWidth='3'
				strokeLinecap='round'
			/>
			<line
				x1='142'
				y1='92'
				x2='166'
				y2='92'
				stroke='var(--bdr)'
				strokeWidth='3'
				strokeLinecap='round'
			/>
			<line
				x1='142'
				y1='102'
				x2='166'
				y2='102'
				stroke='var(--bdr)'
				strokeWidth='3'
				strokeLinecap='round'
			/>
			<path
				d='M72 88 L86 88 L92 78 L100 98 L108 88 L128 88'
				stroke='var(--acc)'
				strokeWidth='4'
				strokeLinecap='round'
				strokeLinejoin='round'
				fill='none'
			/>
			<circle
				cx='100'
				cy='38'
				r='16'
				fill='var(--yellow-l)'
				stroke='var(--yellow)'
				strokeWidth='2.5'
			/>
			<text
				x='100'
				y='44'
				textAnchor='middle'
				fontSize='16'
				fontWeight='800'
				fill='var(--yellow)'
			>
				!
			</text>
		</>
	);
}

function ServiceUnavailableArt() {
	return (
		<>
			<circle
				cx='100'
				cy='80'
				r='70'
				fill='var(--teal-l)'
				opacity='0.45'
			/>
			<rect
				x='56'
				y='34'
				width='88'
				height='96'
				rx='10'
				fill='var(--sur)'
				stroke='var(--bdr)'
				strokeWidth='2.5'
			/>
			<rect
				x='70'
				y='50'
				width='60'
				height='18'
				rx='4'
				fill='var(--gray-l)'
				stroke='var(--bdr)'
				strokeWidth='2'
			/>
			<circle
				cx='80'
				cy='59'
				r='3'
				fill='var(--p)'
			/>
			<rect
				x='70'
				y='76'
				width='60'
				height='18'
				rx='4'
				fill='var(--gray-l)'
				stroke='var(--bdr)'
				strokeWidth='2'
			/>
			<circle
				cx='80'
				cy='85'
				r='3'
				fill='var(--yellow)'
			/>
			<rect
				x='70'
				y='102'
				width='60'
				height='18'
				rx='4'
				fill='var(--gray-l)'
				stroke='var(--bdr)'
				strokeWidth='2'
			/>
			<circle
				cx='80'
				cy='111'
				r='3'
				fill='var(--red)'
			/>
			<circle
				cx='146'
				cy='122'
				r='26'
				fill='var(--sur)'
				stroke='var(--acc)'
				strokeWidth='4'
			/>
			<line
				x1='146'
				y1='122'
				x2='146'
				y2='108'
				stroke='var(--acc)'
				strokeWidth='4'
				strokeLinecap='round'
			/>
			<line
				x1='146'
				y1='122'
				x2='156'
				y2='128'
				stroke='var(--acc)'
				strokeWidth='4'
				strokeLinecap='round'
			/>
		</>
	);
}
